/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package proyecto1progra3.CapaPresentacion;

import java.awt.Color;
import java.awt.Image;
import java.util.Objects;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import proyecto1progra3.CapaLógica.StLog;

/**
 *
 * @author emanu
 */
public class CrearPersona extends javax.swing.JDialog {
StLog Alg = new StLog();
    /**
     * Creates new form CrearPersona
     */
    public CrearPersona(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setTitle("Añadir nueva Persona");
        redimensionar();
        Empezar();

        
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jProfesor = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jComboBox2 = new javax.swing.JComboBox<>();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jButtonGuardar = new javax.swing.JButton();
        jPanelFondo = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanelDatos = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jTFName = new javax.swing.JTextField();
        jTFA1 = new javax.swing.JTextField();
        jTXA2 = new javax.swing.JTextField();
        jTXages = new javax.swing.JTextField();
        jTXCarne = new javax.swing.JTextField();
        jTFDNI = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jPanel1 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jFI = new javax.swing.JTextField();
        jPromedio = new javax.swing.JTextField();
        jClasesActuales = new javax.swing.JTextField();
        jNumero = new javax.swing.JTextField();
        jCorreo = new javax.swing.JTextField();
        jMateriasPasadas = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jDescripcion = new javax.swing.JTextArea();
        jGuardar = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jProfesor.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Bienvenido al sistema de creación de profesores");
        jProfesor.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 20, 620, -1));

        jLabel11.setText("Profesion");
        jProfesor.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 50, -1, -1));

        jLabel12.setText("Universidad de egresión:");
        jProfesor.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 90, -1, -1));

        jLabel13.setText("Clases que imparte");
        jProfesor.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 130, -1, -1));

        jLabel14.setText("Años de experiencia");
        jProfesor.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 160, 110, 30));

        jLabel15.setText("Idiomas");
        jProfesor.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 50, -1, -1));

        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel16.setText("Numero telefónico");
        jProfesor.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 90, -1, -1));

        jLabel17.setText("Correo electrónico");
        jProfesor.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 140, -1, -1));

        jLabel18.setText("Nombre de usuario");
        jProfesor.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 180, -1, -1));

        jTextField1.setText("jTextField1");
        jTextField1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextField1MouseClicked(evt);
            }
        });
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        jProfesor.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 50, 240, -1));

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione la U de donde se graduó", "UNA", "UCR", "TEC", "Latina", "Hispanoamericana", "San José", "Otra" }));
        jProfesor.add(jComboBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 90, 200, -1));

        jTextField2.setText("jTextField2");
        jTextField2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextField2MouseClicked(evt);
            }
        });
        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });
        jProfesor.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 130, 220, -1));

        jTextField3.setText("jTextField3");
        jTextField3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextField3MouseClicked(evt);
            }
        });
        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });
        jProfesor.add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 170, 220, -1));

        jTextField4.setText("jTextField4");
        jTextField4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextField4MouseClicked(evt);
            }
        });
        jTextField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField4ActionPerformed(evt);
            }
        });
        jProfesor.add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 50, 230, -1));

        jTextField5.setText("jTextField5");
        jTextField5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextField5MouseClicked(evt);
            }
        });
        jTextField5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField5ActionPerformed(evt);
            }
        });
        jProfesor.add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 90, 190, -1));

        jTextField6.setText("jTextField6");
        jTextField6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextField6MouseClicked(evt);
            }
        });
        jTextField6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField6ActionPerformed(evt);
            }
        });
        jProfesor.add(jTextField6, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 140, 180, -1));

        jTextField7.setText("jTextField7");
        jTextField7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextField7MouseClicked(evt);
            }
        });
        jTextField7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField7ActionPerformed(evt);
            }
        });
        jProfesor.add(jTextField7, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 180, 180, -1));

        jButtonGuardar.setText("Guardar Datos");
        jButtonGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGuardarActionPerformed(evt);
            }
        });
        jProfesor.add(jButtonGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 340, -1, -1));

        jPanelFondo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(Objects.requireNonNull(getClass().getResource("/proyecto1progra3/Multimedia/CrearPersona.jpg")))); // NOI18N
        jPanelFondo.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 790, 550));

        jPanelDatos.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setBackground(new java.awt.Color(0, 204, 204));
        jLabel2.setForeground(new java.awt.Color(153, 102, 0));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Matricula de esta prestigiosa Universidad");
        jPanelDatos.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 16, 218, -1));

        jLabel3.setText("Nombre");
        jPanelDatos.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 60, 58, -1));

        jLabel4.setText("Apellido 1:");
        jPanelDatos.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 97, -1, -1));

        jLabel5.setText("Apellido 2:");
        jPanelDatos.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 137, -1, -1));

        jLabel6.setText("Edad");
        jPanelDatos.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 177, -1, -1));

        jLabel7.setText("Carnet");
        jPanelDatos.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 217, -1, -1));

        jLabel8.setText("Cedula:");
        jPanelDatos.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 257, -1, -1));

        jTFName.setText("jTextField1");
        jTFName.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTFNameMouseClicked(evt);
            }
        });
        jTFName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFNameActionPerformed(evt);
            }
        });
        jPanelDatos.add(jTFName, new org.netbeans.lib.awtextra.AbsoluteConstraints(64, 57, 160, -1));

        jTFA1.setText("jTextField1");
        jTFA1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTFA1MouseClicked(evt);
            }
        });
        jTFA1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFA1ActionPerformed(evt);
            }
        });
        jPanelDatos.add(jTFA1, new org.netbeans.lib.awtextra.AbsoluteConstraints(74, 97, 150, -1));

        jTXA2.setText("jTextField3");
        jTXA2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTXA2MouseClicked(evt);
            }
        });
        jTXA2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTXA2ActionPerformed(evt);
            }
        });
        jPanelDatos.add(jTXA2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 140, 150, -1));

        jTXages.setText("jTextField4");
        jTXages.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTXagesMouseClicked(evt);
            }
        });
        jTXages.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTXagesActionPerformed(evt);
            }
        });
        jPanelDatos.add(jTXages, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, 180, -1));

        jTXCarne.setText("jTextField5");
        jTXCarne.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTXCarneMouseClicked(evt);
            }
        });
        jTXCarne.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTXCarneActionPerformed(evt);
            }
        });
        jPanelDatos.add(jTXCarne, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 220, 160, -1));

        jTFDNI.setText("jTextField6");
        jTFDNI.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTFDNIMouseClicked(evt);
            }
        });
        jTFDNI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFDNIActionPerformed(evt);
            }
        });
        jPanelDatos.add(jTFDNI, new org.netbeans.lib.awtextra.AbsoluteConstraints(54, 257, 170, -1));

        jLabel9.setText("Tipo de persona a matricular:");
        jPanelDatos.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 297, -1, -1));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pulsa aqui y selecciona alguna de las opciones", "Profesor", "Alumno" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        jPanelDatos.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 319, 218, -1));

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel19.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 0, 153));
        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel19.setText("Bienvenido al panel de creacion de alumnos");
        jPanel1.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 790, 120));

        jLabel20.setText("Fecha de ingreso");
        jPanel1.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, -1, -1));

        jLabel21.setText("Promedio");
        jPanel1.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, -1, -1));

        jLabel23.setText("Materias pasadas");
        jPanel1.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 140, -1, -1));

        jLabel22.setText("Clases actuales");
        jPanel1.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, -1, -1));

        jLabel24.setText("Numero");
        jPanel1.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 190, -1, -1));

        jLabel25.setText("Correo");
        jPanel1.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 240, -1, -1));

        jFI.setText("jTextField8");
        jFI.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jFIMouseClicked(evt);
            }
        });
        jFI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFIActionPerformed(evt);
            }
        });
        jPanel1.add(jFI, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 140, 250, -1));

        jPromedio.setText("jTextField9");
        jPromedio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPromedioMouseClicked(evt);
            }
        });
        jPromedio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPromedioActionPerformed(evt);
            }
        });
        jPanel1.add(jPromedio, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 190, 250, -1));

        jClasesActuales.setText("jTextField10");
        jClasesActuales.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jClasesActualesMouseClicked(evt);
            }
        });
        jClasesActuales.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jClasesActualesActionPerformed(evt);
            }
        });
        jPanel1.add(jClasesActuales, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 240, 250, -1));

        jNumero.setText("jTextField11");
        jNumero.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jNumeroMouseClicked(evt);
            }
        });
        jNumero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jNumeroActionPerformed(evt);
            }
        });
        jPanel1.add(jNumero, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 190, 240, -1));

        jCorreo.setText("jTextField11");
        jCorreo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jCorreoMouseClicked(evt);
            }
        });
        jCorreo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCorreoActionPerformed(evt);
            }
        });
        jPanel1.add(jCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 240, 240, -1));

        jMateriasPasadas.setText("jTextField11");
        jMateriasPasadas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMateriasPasadasMouseClicked(evt);
            }
        });
        jMateriasPasadas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMateriasPasadasActionPerformed(evt);
            }
        });
        jPanel1.add(jMateriasPasadas, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 140, 240, -1));

        jLabel26.setText("Descripción");
        jPanel1.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 320, -1, -1));

        jDescripcion.setColumns(20);
        jDescripcion.setRows(5);
        jDescripcion.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                jDescripcionAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jDescripcion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jDescripcionMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jDescripcion);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 290, 560, -1));

        jGuardar.setText("Guardar");
        jGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jGuardarActionPerformed(evt);
            }
        });
        jPanel1.add(jGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 320, -1, -1));

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Cerrar");
        jMenu2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu2ActionPerformed(evt);
            }
        });
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanelDatos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelFondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addGap(0, 240, Short.MAX_VALUE)
                    .addComponent(jProfesor, javax.swing.GroupLayout.PREFERRED_SIZE, 780, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addGap(0, 230, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 790, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelDatos, javax.swing.GroupLayout.DEFAULT_SIZE, 552, Short.MAX_VALUE)
            .addComponent(jPanelFondo, javax.swing.GroupLayout.DEFAULT_SIZE, 552, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jProfesor, javax.swing.GroupLayout.PREFERRED_SIZE, 540, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 552, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTFNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFNameActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jTFNameActionPerformed

    private void jTFA1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFA1ActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jTFA1ActionPerformed

    private void jTXA2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTXA2ActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jTXA2ActionPerformed

    private void jTXagesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTXagesActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jTXagesActionPerformed

    private void jTXCarneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTXCarneActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jTXCarneActionPerformed

    private void jTFDNIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFDNIActionPerformed
        // TODO add your handling code here:
       
    }//GEN-LAST:event_jTFDNIActionPerformed

    private void jTFNameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTFNameMouseClicked
        // TODO add your handling code here:
        cerrarjTextfielsds(jTFName);
    }//GEN-LAST:event_jTFNameMouseClicked

    private void jTFA1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTFA1MouseClicked
        // TODO add your handling code here:
         cerrarjTextfielsds(jTFA1);
    }//GEN-LAST:event_jTFA1MouseClicked

    private void jTXA2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTXA2MouseClicked
        // TODO add your handling code here:
        cerrarjTextfielsds(jTXA2);
    }//GEN-LAST:event_jTXA2MouseClicked

    private void jTXagesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTXagesMouseClicked
        // TODO add your handling code here:
        cerrarjTextfielsds(jTXages);
    }//GEN-LAST:event_jTXagesMouseClicked

    private void jTXCarneMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTXCarneMouseClicked
        // TODO add your handling code here:
        cerrarjTextfielsds(jTXCarne);
    }//GEN-LAST:event_jTXCarneMouseClicked

    private void jTFDNIMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTFDNIMouseClicked
        // TODO add your handling code here:
         cerrarjTextfielsds(jTFDNI);
         
    }//GEN-LAST:event_jTFDNIMouseClicked

    private void jButtonGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGuardarActionPerformed
        // TODO add your handling code here:
        comprobar(1);
        guardar();
        //mensajesfields();
    }//GEN-LAST:event_jButtonGuardarActionPerformed

    private void jMenu2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu2ActionPerformed
        // TODO add your handling code here:
        this.dispose();
        
    }//GEN-LAST:event_jMenu2ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
     Combobox();   // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jGuardarActionPerformed
        // TODO add your handling code here:
        comprobar(2);
        guardar();
    }//GEN-LAST:event_jGuardarActionPerformed

    private void jPromedioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPromedioActionPerformed
        // TODO add your handling code here:
        cerrarjTextfielsds(jTextField1);
    }//GEN-LAST:event_jPromedioActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
        cerrarjTextfielsds(jTextField1);
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
        cerrarjTextfielsds(jTextField2);
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
        cerrarjTextfielsds(jTextField3);
    }//GEN-LAST:event_jTextField3ActionPerformed

    private void jTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField4ActionPerformed
        // TODO add your handling code here:
        cerrarjTextfielsds(jTextField4);
    }//GEN-LAST:event_jTextField4ActionPerformed

    private void jTextField5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField5ActionPerformed
        // TODO add your handling code here:
        cerrarjTextfielsds(jTextField5);
    }//GEN-LAST:event_jTextField5ActionPerformed

    private void jTextField6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField6ActionPerformed
        // TODO add your handling code here:
        cerrarjTextfielsds(jTextField6);
    }//GEN-LAST:event_jTextField6ActionPerformed

    private void jTextField7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField7ActionPerformed
        // TODO add your handling code here:
        cerrarjTextfielsds(jTextField7);
    }//GEN-LAST:event_jTextField7ActionPerformed

    private void jFIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFIActionPerformed
        // TODO add your handling code here:
        cerrarjTextfielsds(jFI);
    }//GEN-LAST:event_jFIActionPerformed

    private void jClasesActualesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jClasesActualesActionPerformed
        // TODO add your handling code here:
        cerrarjTextfielsds(jClasesActuales);
    }//GEN-LAST:event_jClasesActualesActionPerformed

    private void jMateriasPasadasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMateriasPasadasActionPerformed
        // TODO add your handling code here:
        cerrarjTextfielsds(jMateriasPasadas);
    }//GEN-LAST:event_jMateriasPasadasActionPerformed

    private void jNumeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jNumeroActionPerformed
        // TODO add your handling code here:
        cerrarjTextfielsds(jNumero);
    }//GEN-LAST:event_jNumeroActionPerformed

    private void jCorreoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCorreoActionPerformed
        // TODO add your handling code here:
        cerrarjTextfielsds(jCorreo);
    }//GEN-LAST:event_jCorreoActionPerformed

    private void jDescripcionAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jDescripcionAncestorAdded
        // TODO add your handling code here:
        jDescripcion.setText("");
    }//GEN-LAST:event_jDescripcionAncestorAdded

    private void jFIMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jFIMouseClicked
        cerrarjTextfielsds(jFI);
        // TODO add your handling code here:
    }//GEN-LAST:event_jFIMouseClicked

    private void jPromedioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPromedioMouseClicked
        // TODO add your handling code here:
        cerrarjTextfielsds(jPromedio);
    }//GEN-LAST:event_jPromedioMouseClicked

    private void jClasesActualesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jClasesActualesMouseClicked
        // TODO add your handling code here:
        cerrarjTextfielsds(jClasesActuales);
    }//GEN-LAST:event_jClasesActualesMouseClicked

    private void jMateriasPasadasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMateriasPasadasMouseClicked
        // TODO add your handling code here:
        cerrarjTextfielsds(jMateriasPasadas);
    }//GEN-LAST:event_jMateriasPasadasMouseClicked

    private void jNumeroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jNumeroMouseClicked
        // TODO add your handling code here:
        cerrarjTextfielsds(jNumero);
    }//GEN-LAST:event_jNumeroMouseClicked

    private void jCorreoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jCorreoMouseClicked
        // TODO add your handling code here:
        cerrarjTextfielsds(jCorreo);
    }//GEN-LAST:event_jCorreoMouseClicked

    private void jDescripcionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jDescripcionMouseClicked
        // TODO add your handling code here:
        jDescripcion.setText("");
    }//GEN-LAST:event_jDescripcionMouseClicked

    private void jTextField1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField1MouseClicked
        // TODO add your handling code here:
        cerrarjTextfielsds(jTextField1);
    }//GEN-LAST:event_jTextField1MouseClicked

    private void jTextField2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField2MouseClicked
        // TODO add your handling code here:
        cerrarjTextfielsds(jTextField2);
    }//GEN-LAST:event_jTextField2MouseClicked

    private void jTextField3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField3MouseClicked
        // TODO add your handling code here:
        cerrarjTextfielsds(jTextField3);
    }//GEN-LAST:event_jTextField3MouseClicked

    private void jTextField4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField4MouseClicked
        // TODO add your handling code here:
        cerrarjTextfielsds(jTextField4);
    }//GEN-LAST:event_jTextField4MouseClicked

    private void jTextField5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField5MouseClicked
        // TODO add your handling code here:
        cerrarjTextfielsds(jTextField5);
    }//GEN-LAST:event_jTextField5MouseClicked

    private void jTextField6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField6MouseClicked
        // TODO add your handling code here:
        cerrarjTextfielsds(jTextField6);
    }//GEN-LAST:event_jTextField6MouseClicked

    private void jTextField7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField7MouseClicked
        // TODO add your handling code here:
        cerrarjTextfielsds(jTextField7);
    }//GEN-LAST:event_jTextField7MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CrearPersona.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CrearPersona.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CrearPersona.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CrearPersona.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                CrearPersona dialog = new CrearPersona(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonGuardar;
    private javax.swing.JTextField jClasesActuales;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JTextField jCorreo;
    private javax.swing.JTextArea jDescripcion;
    private javax.swing.JTextField jFI;
    private javax.swing.JButton jGuardar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jMateriasPasadas;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JTextField jNumero;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanelDatos;
    private javax.swing.JPanel jPanelFondo;
    private javax.swing.JPanel jProfesor;
    private javax.swing.JTextField jPromedio;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTFA1;
    private javax.swing.JTextField jTFDNI;
    private javax.swing.JTextField jTFName;
    private javax.swing.JTextField jTXA2;
    private javax.swing.JTextField jTXCarne;
    private javax.swing.JTextField jTXages;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    // End of variables declaration//GEN-END:variables

    private void redimensionar() {
        ImageIcon icon = new ImageIcon("C:\\Users\\emanu\\IdeaProjects\\Proyecto1Progralll\\Proyecto1Progra3\\src\\proyecto1progra3\\Multimedia\\CrearPersona.jpg");
Image image = icon.getImage().getScaledInstance(jLabel1.getWidth(), jLabel1.getHeight(), Image.SCALE_SMOOTH);
icon = new ImageIcon(image);
jLabel1.setIcon(icon);

    }

    private void cerrarjTextfielsds(JTextField componente){
        componente.setText("");
        componente.setForeground(new Color(0,0,0));
    }

    private void guardar() {
        //Franco o Harold, no sé quien va a hacer el Backend, pero aqui va el método que guarda los datos a la base de datos.
        Alg.Agregar(jFI.getText(),jClasesActuales.getText(),jMateriasPasadas.getText(),Integer.parseInt(jTXCarne.getText()) , Integer.parseInt(jTFDNI.getText()), jTFName.getText(), jTFA1.getText(), jTXA2.getText(), Integer.parseInt(jTXages.getText()), jCorreo.getText(),Integer.parseInt(jPromedio.getText()), jDescripcion.getText(), Integer.parseInt(jNumero.getText()));
         Gestion g = new Gestion(null, true);
         g.CargardatosBasedeDatos();
        
    }

    private void Combobox() {
        if(jComboBox1.getSelectedIndex() == 1 ){
            empezarProfesor();
            setTitle("Hola, " + jTFName.getText()+ ". Termine de configurar su perfil");
            mensajesfields(jTextField1, "¿A que se dedica este profesor?");
            jComboBox2.setSelectedIndex(0);
            mensajesfields(jTextField2, "¿Que clases impartira este profesor?");
            mensajesfields(jTextField3, "Cuantos años lleva laburando?");
            mensajesfields(jTextField4, "Idiomas");
            mensajesfields(jTextField5, "Numero del profe");
            mensajesfields(jTextField6, "El @ulatina.net del profesor");
            mensajesfields(jTextField7, "El Username (Nombre de Usuario)");
        }
        if(jComboBox1.getSelectedIndex() ==0){
            JOptionPane.showMessageDialog(null,"Seleccione una opcion");
        }
        if(jComboBox1.getSelectedIndex()==2){
            EmpezarAlumno();
            mensajesfields(jFI, "Fecha de ingreso");
            mensajesfields(jPromedio, "Promedio del estudiante");
            mensajesfields(jClasesActuales, "Clases que lleva");
            mensajesfields(jMateriasPasadas, "Materias con promedio +70");
            mensajesfields(jNumero, "Numero telefonico");
            mensajesfields(jCorreo, "Correo personal del estudiante");
            jDescripcion.setText(" ");
            jDescripcion.setForeground(Color.BLUE);

            
        }
        
    }

    private void empezarProfesor() {
        jPanelFondo.setVisible(false);
        jComboBox2.setSelectedIndex(0);
        jPanel1.setVisible(false);
        jProfesor.setVisible(true);
    }

    private void mensajesfields(JTextField Campo, String Mensaje) {
        Campo.setText(Mensaje); 
        Campo.setForeground(Color.BLUE);
        
    }

    private void comprobar(int profeoest) {
        
        
        if(profeoest ==1){//Seleccionamos si es profe o no
            String nulo = "";
        if(jTFName.getText().equals(nulo)){
            Unestupidoseequivoco(jLabel3,jTFName, "El primer imbecil qEue no tiene nombre. Revisalo, pedazo");
        }
        if(jTFA1.getText().equals(nulo)){
            Unestupidoseequivoco(jLabel4, jTFA1, "Tu primer apellido es como mi novia (no existe). Revisa antes de enviar");
        }
        if(jTFA1.getText().equals(nulo)){
            Unestupidoseequivoco(jLabel5, jTXA2, "Tu segundo apellido es como mi novia (no existe). Revisa antes de enviar");
    }
        if(jTFDNI.getText().equals(nulo)){
            Unestupidoseequivoco(jLabel8, jTFDNI, "Que? No estas en el registro o que?");
        }
        if(jTXages.getText().equals(nulo)){
            Unestupidoseequivoco(jLabel16, jTXages ,"Que? aun estas en el utero de tu mamá?");
        }
        comprobarint(jTXages);
        comprobarint(jTXCarne);
        if(jTextField1.getText().equals(nulo)){
            Unestupidoseequivoco(jLabel1, jTextField1,"Digite una opcion de trabajo");
        }
        if(jTextField2.getText().equals(nulo)){
            Unestupidoseequivoco(jLabel2,jTextField2,"Digite una opcion de clases");
        }
        if(jTextField3.getText().equals(nulo)) {
        Unestupidoseequivoco(jLabel3,jTextField3,"Digite una opcion de trabajo anterior");
        }
        if(jTextField4.getText().equals(nulo)){
            Unestupidoseequivoco(jLabel4,jTextField4,"Digite una opcion de idiomas");
        }
        if(jTextField5.getText().equals(nulo)){
            Unestupidoseequivoco(jLabel5,jTextField5, "Estamos en la prehistoria?");
        }
        if(jTextField6.getText().equals(nulo)){
            Unestupidoseequivoco(jLabel6,jTextField6, "El mae es Tom Cruise? porque todo el mundo tiene email");
        }
        if(jTextField7.getText().equals(nulo) ){
            Unestupidoseequivoco(jLabel7,jTextField7,"El mae no se ha registrado?");
        }
        comprobarint(jTextField3);
        comprobarint(jTextField5);


    }
            if(profeoest ==2){//Seleccionamos que queremos aplicar esto en estudiantes
                //Poner aqui los errores de estudiantes
                String nulo = "";
                if(jTFName.getText().equals(nulo)){
                    Unestupidoseequivoco(jLabel3,jTFName, "El primer imbecil qEue no tiene nombre. Revisalo, pedazo");
                }
                if(jTFA1.getText().equals(nulo)){
                    Unestupidoseequivoco(jLabel4, jTFA1, "Tu primer apellido es como mi novia (no existe). Revisa antes de enviar");
                }
                if(jTFA1.getText().equals(nulo)){
                    Unestupidoseequivoco(jLabel5, jTXA2, "Tu segundo apellido es como mi novia (no existe). Revisa antes de enviar");
                }
                if(jTFDNI.getText().equals(nulo)){
                    Unestupidoseequivoco(jLabel8, jTFDNI, "Que? No estas en el registro o que?");
                }
                if(jTXages.getText().equals(nulo)){
                    Unestupidoseequivoco(jLabel16, jTXages ,"Que? aun estas en el utero de tu mamá?");
                }
                comprobarint(jTXages);
                comprobarint(jTXCarne);
                if(jFI.getText().equals(nulo)){
                    JOptionPane.showMessageDialog(null, "Parece que el alumno ni se ha matriculado, porque no diste fecha de ingreso, animal");
                }
                if(jPromedio.getText().equals(nulo)){
                    Unestupidoseequivoco(jLabel21, jPromedio, "Que? El alumno es tan estúpido como el que está haciendo esto?");
                }
                if(jClasesActuales.getText().equals(nulo)){
                    Unestupidoseequivoco(jLabel22, jClasesActuales, "Que? El alumno no lleva materias este cuatri?");
                }
                if(jMateriasPasadas.getText().equals(nulo)){
                    Unestupidoseequivoco(jLabel23, jMateriasPasadas, "Este alumno que? No ha pasado materias?");
                }
                if(jNumero.getText().equals(nulo)){
                    Unestupidoseequivoco(jLabel24, jNumero, "Este mae vive en la prehistoria o que?");

                }
                comprobarPromedio(jPromedio);
                comprobarint(jNumero);
                if(jCorreo.getText().equals(nulo)){
                    Unestupidoseequivoco(jLabel25, jCorreo, "Este mae vive en la prehistoria? Porque hoy en dia se usa el correo");
                }
                if(jDescripcion.getText().equals(nulo)){
                    jLabel26.setForeground(new Color(255,0,0));
                    JOptionPane.showMessageDialog(null, "No veo la descripcion del tipo");
                }
            }
        }

    private void comprobarPromedio(JTextField jPromedio) {
    if(isNumeric(jPromedio.getText())){
        System.out.printf("No se ha equivocado");
    } else {
        Unestupidoseequivoco(jLabel21,jPromedio,"digite correctamente el promedio");
    }
    }

    private boolean isFloat(String text) {
        try {
            Float.parseFloat(text);
            System.out.println("No se ha equivocado");
            } catch(NumberFormatException e){

            }
        return false;
    }


    private void Unestupidoseequivoco(JLabel etiqueta, JTextField CasillaEquivocada, String Mensajealestupido) {
        int rojo = 255; int verdeazul = 0;
        JOptionPane.showMessageDialog(null, Mensajealestupido);
        etiqueta.setForeground(new Color(rojo,verdeazul,verdeazul));
        
    }

    private void EmpezarAlumno() {
        jPanel1.setVisible(true);
        jComboBox1.setSelectedItem(2);
        jPanelFondo.setVisible(false);
        jProfesor.setVisible(false);
    }

    private void comprobarint(JTextField mensajeacomprobar) {
        if(isNumeric(mensajeacomprobar.getText())){
            System.out.println("No se ha equivocado");
            
        }
        else{
            JOptionPane.showMessageDialog(null, "Digite correctamente los daros"+mensajeacomprobar.getText());
        }
    }
    public static boolean isNumeric(String str) {//Comprobamos si un dato ingresado es entero
    try {
        Integer.parseInt(str);
        return true;
    } catch (NumberFormatException e) {
        return false;
    }
}

    private void Empezar() {
        mensajesfields(jTFName, "Digite su nombre");
        mensajesfields(jTFA1, "Digita su primer apellido");
        mensajesfields(jTXA2, "Digita su segundo apellido");
        mensajesfields(jTXages, "Su edad");
        mensajesfields(jTXCarne, "Su carne universitario");
        mensajesfields(jTFDNI, "Su cedula");
    }

  
    

}
